### PR TITLE
Change licence from Apache 2.0 to GNU GPL 3.0

### PR DESCRIPTION
**Pull request by LudovicRousseau**
This is part of https://github.com/Pirionfr/pyLinky/issues/9

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
Hello,
Do you plan to merge this PR?

**Comment by Pirionfr** [comment]
I'm checking impact for other project

**Comment by Pirionfr** [comment]
no need anymore

**Comment by LudovicRousseau** [comment]
I still have 2 patches from https://github.com/empierre/domoticz_linky that have not been submitted to pyLinky because of the licence incompatibility.
They are minor changes for error cases so not really mandatory.

**Pull request closed without merging**
