### PR TITLE
export internal methods

### PR DESCRIPTION
**Pull request by LudovicRousseau**
Add LinkyClient.login() method
Export format_data()
client.py: start and end date are now in datetime.date format

### CODE REVIEW

**Review by Pirionfr — COMMENTED** [review]
maybe we can change line 192 with your login function

**Comment by LudovicRousseau** [comment]
Yes, you could call `.login()` from inside `.fetch_data()`.

Personally I prefer to have disctincts methods and call them explicitly.
The sequence would be:
```
.login()
.fetch_data()
.get_data()
```

**Comment by Pirionfr** [comment]
ok fine for me, we can modify the main to do it
can you do the modification ?

**Comment by Pirionfr** [comment]
It will be integrate in v0.3.0

**Pull request merged**
